/* eslint-disable */
/**
 * Talisman phonetics/french/fonem tests
 * ======================================
 *
 */
import assert from 'assert';
import fonem from '../../../src/phonetics/french/fonem';

describe('fonem', function() {
  it('should throw if the given word is not a string.', function() {
    assert.throws(function() {
      fonem([]);
    }, /string/);
  });

  it('should compute the fonem code correctly.', function() {
    const tests = [
      ['BEAULAC', 'BOLAC'],
      ['BAULAC', 'BOLAC'],
      ['IMBEAULT', 'IMBO'],
      ['DUFAUT', 'DUFO'],
      ['THIBOUTOT', 'TIBOUTOT'],
      ['DEVAUX', 'DEVO'],
      ['RONDEAUX', 'RONDO'],
      ['BOURGAULX', 'BOURGO'],
      ['PINCHAUD', 'PINCHO'],
      ['PEDNAULD', 'PEDNO'],
      ['MAZENOD', 'MAZENOD'],
      ['ARNOLD', 'ARNOLD'],
      ['BERTOLD', 'BERTOLD'],
      ['BELLAY', 'BELLE'],
      ['SANDAY', 'SANDE'],
      ['GAY', 'GAY'],
      ['FAYARD', 'FAYAR'],
      ['LEMIEUX', 'LEMIEU'],
      ['LHEUREUX', 'LHEUREU'],
      ['BELLEY', 'BELLE'],
      ['WELLEY', 'WELLE'],
      ['MEYER', 'MEYER'],
      ['BOILY', 'BOILI'],
      ['LOYSEAU', 'LOISEAU'],
      ['MAYRAND', 'MAIRAND'],
      ['GUYON', 'GUYON'],
      ['FAILLARD', 'FAYARD'],
      ['MEILLER', 'MEYER'],
      ['GUILLON', 'GUYON'],
      ['LAVILLE', 'LAVILLE'],
      ['COUET', 'CWET'],
      ['EDOUARD', 'EDWARD'],
      ['GIROUARD', 'GIRWARD'],
      ['OZOUADE', 'OZWADE'],
      ['BOUILLE', 'BOUILLE'],
      ['POUYEZ', 'POUYEZ'],
      ['LEMEE', 'LEME'],
      ['ABRAAM', 'ABRAM'],
      ['ARCHEMBAULT', 'ARCHENBAULT'],
      ['AMTHIME', 'ENTHIME'],
      ['ROMPRE', 'RONPRE'],
      ['BOMSECOURS', 'BONSECOURS'],
      ['BOULANGER', 'BOULENGER'],
      ['TANCREDE', 'TENCREDE'],
      ['BLAIN', 'BLIN'],
      ['BLAINVILLE', 'BLINVILLE'],
      ['MAINARD', 'MAINARD'],
      ['RAIMOND', 'RAIMOND'],
      ['BLACKBORN', 'BLACKBURN'],
      ['SEABOURNE', 'SEARBURN'],
      ['IMBO', 'INBO'],
      ['RIMFRET', 'RINFRET'],
      ['LEFEVBRE', 'LEFEVRE'],
      ['MACE', 'MASSE'],
      ['MACON', 'MACON'],
      ['MARCELIN', 'MARSELIN'],
      ['MARCEAU', 'MARSEAU'],
      ['VINCELETTE', 'VINSELETTE'],
      ['FORCADE', 'FORCADE'],
      ['CELINE', 'SELINE'],
      ['CERAPHIN', 'SERAPHIN'],
      ['CAYETTE', 'KAYETTE'],
      ['CARINE', 'KARINE'],
      ['LUC', 'LUK'],
      ['LEBLANC', 'LEBLANC'],
      ['VICTOR', 'VIKTOR'],
      ['LACCOULINE', 'LAKOULINE'],
      ['MACCIMILIEN', 'MAXIMILIEN'],
      ['MAGELLA', 'MAJELLA'],
      ['GINETTE', 'JINETTE'],
      ['GANDET', 'GANDET'],
      ['GEORGES', 'JORGES'],
      ['GEOFFROID', 'JOFFROID'],
      ['PAGEAU', 'PAJO'],
      ['GAGNION', 'GAGNON'],
      ['MIGNIER', 'MIGNER'],
      ['HALLEY', 'ALLEY'],
      ['GAUTHIER', 'GAUTIER'],
      ['CHARTIER', 'CHARTIER'],
      ['JEANNE', 'JANNE'],
      ['MACGREGOR', 'MACGREGOR'],
      ['MACKAY', 'MACKAY'],
      ['MCNICOL', 'MACNICOL'],
      ['MCNEIL', 'MACNEIL'],
      ['PHANEUF', 'FANEUF'],
      ['PHILIPPE', 'FILIPPE'],
      ['QUENNEVILLE', 'KENNEVILLE'],
      ['LAROCQUE', 'LAROCKE'],
      ['SCIPION', 'SIPION'],
      ['ASCELIN', 'ASSELIN'],
      ['VASCO', 'VASKO'],
      ['PASCALINE', 'PASKALINE'],
      ['ESHEMBACK', 'ECHEMBACK'],
      ['ASHED', 'ACHED'],
      ['GRATIA', 'GRASSIA'],
      ['PATRITIA', 'PATRISSIA'],
      ['BERTIO', 'BERTIO'],
      ['MATIEU', 'MATIEU'],
      ['BERTIAUME', 'BERTIAUME'],
      ['MUNROW', 'MUNRO'],
      ['BRANISLAW', 'BRANISLA'],
      ['LOWMEN', 'LOMEN'],
      ['ANDREW', 'ANDREW'],
      ['EXCEL', 'EXEL'],
      ['EXCERINE', 'EXERINE'],
      ['EXSILDA', 'EXILDA'],
      ['EXZELDA', 'EXELDA'],
      ['CAZEAU', 'CASEAU'],
      ['BRAZEAU', 'BRASEAU'],
      ['FITZPATRICK', 'FITSPATRICK'],
      ['SINGELAIS', 'ST-GELAIS'],
      ['CINQMARS', 'ST-MARS'],
      ['SAINT-AMAND', 'ST-AMAND'],
      ['SAINTECROIX', 'STE-CROIX'],
      ['ST-HILAIRE', 'ST-HILAIRE'],
      ['STE-CROIX', 'STE-CROIX']
    ];

    tests.forEach(function([word, code]) {
      assert.strictEqual(fonem(word), code, `${word} => ${code}`);
    });
  });
});
